twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        description: 'Annonce'
        name: 'Kim'
        address: '1 Avenue Doyen Quatre Bornes'
        email: 'kimstevine6@gmail.com'
        company: 'Kim'
        telephone: '52740595'
        siret : '11'
        ape: '6201Z'
        price: '500'
        currency: 'euros'
        tva: 'non applicable ART.293B du CGI'
        quantity: '1'
        host: 'ionos'
        domain: 'easywebjob.fr'

when@test:
    twig:
        strict_variables: true
